repos:
  # auto update
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: "v0.3.3post1"
    hooks:
      - id: pre-commit-update
        args: [--dry-run, --all-versions]

  # ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.7"
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.1"
    hooks:
      - id: mypy
        args: [ '--ignore-missing-imports', '--disable-error-code=top-level-await', "--disable-error-code=empty-body" ]
